// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestFulAPI.DataAccess;

#nullable disable

namespace RestFulAPI.DataAccess.Migrations
{
    [DbContext(typeof(RentDbContext))]
    [Migration("20241214160003_RoomContractUpdate")]
    partial class RoomContractUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestFulAPI.Core.Models.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("AverageMark")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("MONEY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBathroomAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWiFiAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("LlId")
                        .HasColumnType("int");

                    b.Property<short>("NumberOfFloors")
                        .HasColumnType("smallint");

                    b.Property<short>("NumberOfRooms")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("LlId");

                    b.ToTable("Flats");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.FlatContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("MONEY");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FlatId")
                        .HasColumnType("int");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("LesseeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("LesseeId");

                    b.ToTable("FlatContracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("AverageMark")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LlId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LlId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("AverageMark")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CostPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("MONEY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsBathroomAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWiFiAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("LlId")
                        .HasColumnType("int");

                    b.Property<short>("NumberOfFloors")
                        .HasColumnType("smallint");

                    b.Property<short>("NumberOfRooms")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("LlId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.HouseContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("MONEY");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("LesseeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("LandlordId");

                    b.HasIndex("LesseeId");

                    b.ToTable("HouseContracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Landlords");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.LandlordAdditionalInfo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("AverageMark")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassportId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId")
                        .IsUnique()
                        .HasFilter("[LandlordId] IS NOT NULL");

                    b.ToTable("LandlordAdditionalInfos");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Lessee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Lessees");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.LesseeAdditionalInfo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("AverageMark")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasDefaultValue(0.0m);

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("LesseeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassportId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LesseeId")
                        .IsUnique();

                    b.ToTable("LesseeAdditionalInfos");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageMark")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<decimal>("CostPerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("MONEY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBathroomAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWiFiAvailable")
                        .HasColumnType("bit");

                    b.Property<short>("NumberOfFloors")
                        .HasColumnType("smallint");

                    b.Property<short>("NumberOfRooms")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.RoomContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("MONEY");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<int>("LesseeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.HasIndex("LesseeId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomContracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Flat", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Landlord", "LandLord")
                        .WithMany("Flats")
                        .HasForeignKey("LlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandLord");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.FlatContract", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Flat", "Flat")
                        .WithMany("Contracts")
                        .HasForeignKey("FlatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestFulAPI.Core.Models.Landlord", "Landlord")
                        .WithMany("FlatContracts")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestFulAPI.Core.Models.Lessee", "Lessee")
                        .WithMany("FlatContracts")
                        .HasForeignKey("LesseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flat");

                    b.Navigation("Landlord");

                    b.Navigation("Lessee");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Hotel", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Landlord", "LandLord")
                        .WithMany("Hotels")
                        .HasForeignKey("LlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandLord");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.House", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Landlord", "LandLord")
                        .WithMany("Houses")
                        .HasForeignKey("LlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LandLord");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.HouseContract", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.House", "House")
                        .WithMany("Contracts")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestFulAPI.Core.Models.Landlord", "Landlord")
                        .WithMany("HouseContracts")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestFulAPI.Core.Models.Lessee", "Lessee")
                        .WithMany("HouseContracts")
                        .HasForeignKey("LesseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("Landlord");

                    b.Navigation("Lessee");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.LandlordAdditionalInfo", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Landlord", "Landlord")
                        .WithOne("AdditionalInfo")
                        .HasForeignKey("RestFulAPI.Core.Models.LandlordAdditionalInfo", "LandlordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.LesseeAdditionalInfo", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Lessee", "Lessee")
                        .WithOne("AdditionalInfo")
                        .HasForeignKey("RestFulAPI.Core.Models.LesseeAdditionalInfo", "LesseeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lessee");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Room", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Hotel", "Hotel")
                        .WithMany("HotelRooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.RoomContract", b =>
                {
                    b.HasOne("RestFulAPI.Core.Models.Landlord", "Landlord")
                        .WithMany("RoomContracts")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestFulAPI.Core.Models.Lessee", "Lessee")
                        .WithMany("RoomContracts")
                        .HasForeignKey("LesseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestFulAPI.Core.Models.Room", "Room")
                        .WithMany("Contracts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landlord");

                    b.Navigation("Lessee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Flat", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Hotel", b =>
                {
                    b.Navigation("HotelRooms");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.House", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Landlord", b =>
                {
                    b.Navigation("AdditionalInfo");

                    b.Navigation("FlatContracts");

                    b.Navigation("Flats");

                    b.Navigation("Hotels");

                    b.Navigation("HouseContracts");

                    b.Navigation("Houses");

                    b.Navigation("RoomContracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Lessee", b =>
                {
                    b.Navigation("AdditionalInfo");

                    b.Navigation("FlatContracts");

                    b.Navigation("HouseContracts");

                    b.Navigation("RoomContracts");
                });

            modelBuilder.Entity("RestFulAPI.Core.Models.Room", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
